services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - frontend
      - api
    links:
      - frontend
      - api

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
  
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:5001:5001"
    volumes:
      - ./api:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:15.3-alpine3.18
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres