version: '3'
services:
  frontend:
    container_name: frontend
    image: frontend
    volumes:
      - ./Fall-Detection-App/frontend/rt-fall-detection:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: ["npm", "start"]
  app:
    image: node:14
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm start